import * as React from "react";

interface DashboardMockupProps {
  className?: string;
}

const KPIS = [
  { label: "Active users", value: "4.2K", delta: "+12%", tone: "success" as const },
  { label: "Conversion", value: "92%", delta: "+3.1%", tone: "success" as const },
  { label: "Sessions", value: "1,238", delta: "-2.4%", tone: "warning" as const },
  { label: "Δ Week", value: "+18.4%", delta: "+5%", tone: "success" as const },
];

const TABLE_ROWS = [
  { tone: "success" as const, nameWidth: 88, label: "ACTIVE" },
  { tone: "brand" as const, nameWidth: 64, label: "TRIAL" },
  { tone: "warning" as const, nameWidth: 96, label: "PENDING" },
];

const NAV_ITEMS = [0, 1, 2, 3, 4];

const toneFill = (t: "success" | "warning" | "brand" | "danger") =>
  t === "success" ? "oklch(72% 0.16 150)"
  : t === "warning" ? "var(--color-accent-500)"
  : t === "brand" ? "var(--color-brand)"
  : "oklch(60% 0.20 25)";

/**
 * DashboardMockup — hand-built SVG illustration of the kind of dashboard
 * shipit-ui-design generates. ALL color values reference semantic tokens,
 * so the illustration adapts to dark mode automatically.
 */
export function DashboardMockup({ className }: DashboardMockupProps) {
  return (
    <svg
      role="img"
      aria-label="Polished dashboard generated by shipit-ui-design"
      viewBox="0 0 720 480"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      preserveAspectRatio="xMidYMid meet"
    >
      <defs>
        <filter id="dm-shadow" x="-10%" y="-10%" width="120%" height="130%" filterUnits="userSpaceOnUse">
          <feGaussianBlur in="SourceAlpha" stdDeviation="10" />
          <feOffset dx="0" dy="14" result="offsetblur" />
          <feComponentTransfer><feFuncA type="linear" slope="0.18" /></feComponentTransfer>
          <feMerge><feMergeNode /><feMergeNode in="SourceGraphic" /></feMerge>
        </filter>
        <linearGradient id="dm-area" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="var(--color-brand-500)" stopOpacity="0.32" />
          <stop offset="100%" stopColor="var(--color-brand-500)" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="dm-spark" x1="0" y1="0" x2="1" y2="0">
          <stop offset="0%" stopColor="var(--color-brand-400)" />
          <stop offset="100%" stopColor="var(--color-accent-400)" />
        </linearGradient>
        <clipPath id="dm-clip">
          <rect x="16" y="16" width="688" height="448" rx="20" ry="20" />
        </clipPath>
      </defs>

      {/* Browser frame */}
      <g filter="url(#dm-shadow)">
        <rect x="16" y="16" width="688" height="448" rx="20" ry="20"
          fill="var(--color-surface)" stroke="var(--color-border)" strokeWidth="1" />
      </g>

      <g clipPath="url(#dm-clip)">
        {/* Title bar */}
        <rect x="16" y="16" width="688" height="36" fill="var(--color-surface-elevated)" />
        <line x1="16" y1="52" x2="704" y2="52" stroke="var(--color-border-subtle)" strokeWidth="1" />
        <circle cx="36" cy="34" r="5.5" fill="var(--color-accent-500)" />
        <circle cx="54" cy="34" r="5.5" fill="var(--color-accent-400)" />
        <circle cx="72" cy="34" r="5.5" fill="var(--color-brand-400)" />
        <rect x="232" y="22" width="256" height="24" rx="12"
          fill="var(--color-surface)" stroke="var(--color-border)" strokeWidth="1" />
        <text x="360" y="38" textAnchor="middle" fontSize="10"
          fontFamily="var(--font-mono)" fill="var(--color-fg-subtle)">
          shipit-ui-design.app/dashboard
        </text>

        {/* Sidebar */}
        <rect x="16" y="52" width="64" height="412" fill="var(--color-surface-elevated)" />
        <line x1="80" y1="52" x2="80" y2="464" stroke="var(--color-border-subtle)" strokeWidth="1" />
        <rect x="32" y="68" width="32" height="32" rx="8" fill="var(--color-brand)" />
        <circle cx="56" cy="92" r="4" fill="var(--color-accent-400)" />
        {NAV_ITEMS.map((i) => {
          const y = 124 + i * 44;
          const active = i === 1;
          return (
            <g key={i}>
              <rect x="32" y={y} width="32" height="32" rx="8"
                fill={active ? "var(--color-brand-50)" : "transparent"}
                stroke={active ? "var(--color-brand-200)" : "transparent"} strokeWidth="1" />
              <NavGlyph index={i} y={y} active={active} />
            </g>
          );
        })}

        {/* Top bar */}
        <rect x="80" y="52" width="624" height="48" fill="var(--color-surface)" />
        <line x1="80" y1="100" x2="704" y2="100" stroke="var(--color-border-subtle)" strokeWidth="1" />
        <rect x="100" y="64" width="240" height="24" rx="12"
          fill="var(--color-surface-elevated)" stroke="var(--color-border-subtle)" strokeWidth="1" />
        <circle cx="114" cy="76" r="4" fill="none" stroke="var(--color-fg-subtle)" strokeWidth="1.5" />
        <line x1="117" y1="79" x2="121" y2="83" stroke="var(--color-fg-subtle)" strokeWidth="1.5" strokeLinecap="round" />
        <rect x="128" y="73" width="80" height="6" rx="3" fill="var(--color-border-subtle)" />
        <circle cx="652" cy="76" r="6" fill="none" stroke="var(--color-fg-muted)" strokeWidth="1.5" />
        <circle cx="656" cy="72" r="2" fill="var(--color-accent-500)" />
        <circle cx="688" cy="76" r="10" fill="var(--color-brand)" />
        <text x="688" y="80" textAnchor="middle" fontSize="9" fontWeight="700" fill="var(--color-fg-on-brand)">RR</text>

        {/* KPI tiles */}
        {KPIS.map((k, i) => (
          <KpiTile key={k.label} x={100 + i * 152} y={116} {...k} />
        ))}

        {/* Chart card */}
        <rect x="100" y="208" width="588" height="148" rx="12"
          fill="var(--color-surface)" stroke="var(--color-border-subtle)" strokeWidth="1" />
        <text x="116" y="228" fontSize="11" fontWeight="700" fill="var(--color-fg)">Revenue</text>
        <text x="116" y="242" fontSize="9" fill="var(--color-fg-subtle)">Last 30 days · USD</text>
        <rect x="624" y="218" width="48" height="18" rx="9"
          fill="var(--color-surface-elevated)" stroke="var(--color-border-subtle)" strokeWidth="1" />
        <text x="648" y="230" textAnchor="middle" fontSize="9" fill="var(--color-fg-muted)">30d</text>
        {[260, 290, 320].map((y) => (
          <line key={y} x1="116" y1={y} x2="672" y2={y}
            stroke="var(--color-border-subtle)" strokeWidth="1" strokeDasharray="2 4" />
        ))}
        <path
          d="M116,316 L160,302 L204,308 L248,288 L292,294 L336,272 L380,278 L424,260 L468,266 L512,250 L556,240 L600,248 L644,232 L672,224 L672,344 L116,344 Z"
          fill="url(#dm-area)"
        />
        <polyline
          points="116,316 160,302 204,308 248,288 292,294 336,272 380,278 424,260 468,266 512,250 556,240 600,248 644,232 672,224"
          fill="none" stroke="var(--color-brand-500)" strokeWidth="2"
          strokeLinecap="round" strokeLinejoin="round"
        />
        {[[248, 288], [424, 260], [600, 248]].map(([cx, cy]) => (
          <g key={`${cx}-${cy}`}>
            <circle cx={cx} cy={cy} r="5" fill="var(--color-surface)"
              stroke="var(--color-brand-500)" strokeWidth="2" />
            <circle cx={cx} cy={cy} r="2" fill="var(--color-brand-500)" />
          </g>
        ))}

        {/* Table */}
        <rect x="100" y="368" width="588" height="84" rx="12"
          fill="var(--color-surface)" stroke="var(--color-border-subtle)" strokeWidth="1" />
        {TABLE_ROWS.map((r, i) => (
          <TableRow key={i} y={380 + i * 24} {...r} />
        ))}
      </g>
    </svg>
  );
}

function NavGlyph({ index, y, active }: { index: number; y: number; active: boolean }) {
  const stroke = active ? "var(--color-brand)" : "var(--color-fg-muted)";
  if (index === 0)
    return <rect x="42" y={y + 10} width="12" height="12" rx="2"
      fill="none" stroke={stroke} strokeWidth="1.5" />;
  if (index === 1)
    return (
      <g fill="var(--color-brand)">
        <rect x="42" y={y + 10} width="12" height="5" rx="1.5" />
        <rect x="42" y={y + 17} width="12" height="5" rx="1.5" opacity="0.6" />
      </g>
    );
  if (index === 2)
    return <circle cx="48" cy={y + 16} r="6" fill="none" stroke={stroke} strokeWidth="1.5" />;
  if (index === 3)
    return <path d={`M42 ${y + 22} L48 ${y + 12} L54 ${y + 22} Z`}
      fill="none" stroke={stroke} strokeWidth="1.5" strokeLinejoin="round" />;
  return (
    <g stroke={stroke} strokeWidth="1.5" strokeLinecap="round">
      <line x1="42" y1={y + 13} x2="54" y2={y + 13} />
      <line x1="42" y1={y + 17} x2="54" y2={y + 17} />
      <line x1="42" y1={y + 21} x2="50" y2={y + 21} />
    </g>
  );
}

function KpiTile({ x, y, label, value, delta, tone }: {
  x: number; y: number; label: string; value: string; delta: string;
  tone: "success" | "warning" | "danger";
}) {
  const fill = toneFill(tone);
  const isDown = tone === "warning";
  return (
    <g>
      <rect x={x} y={y} width="136" height="76" rx="12"
        fill="var(--color-surface)" stroke="var(--color-border-subtle)" strokeWidth="1" />
      <text x={x + 14} y={y + 22} fontSize="9" fill="var(--color-fg-subtle)" fontWeight="500">
        {label.toUpperCase()}
      </text>
      <text x={x + 14} y={y + 50} fontSize="20" fontWeight="800" fill="var(--color-fg)">{value}</text>
      <rect x={x + 14} y={y + 56} width="44" height="14" rx="7" fill={fill} opacity="0.14" />
      <path d={isDown ? `M${x + 22} ${y + 60} l3 4 l3 -4 Z` : `M${x + 22} ${y + 67} l3 -4 l3 4 Z`}
        fill={fill} />
      <text x={x + 32} y={y + 67} fontSize="9" fontWeight="700" fill={fill}>{delta}</text>
    </g>
  );
}

function TableRow({ y, tone, nameWidth, label }: {
  y: number; tone: "success" | "warning" | "brand"; nameWidth: number; label: string;
}) {
  const fill = toneFill(tone);
  return (
    <g>
      <circle cx={124} cy={y + 8} r="8" fill="var(--color-surface-elevated)"
        stroke="var(--color-border)" strokeWidth="1" />
      <rect x={140} y={y + 4} width={nameWidth} height="8" rx="3"
        fill="var(--color-fg-muted)" opacity="0.55" />
      <rect x={140} y={y + 14} width={nameWidth - 16} height="5" rx="2.5" fill="var(--color-border)" />
      <rect x={400} y={y + 4} width="56" height="14" rx="7" fill={fill} opacity="0.14" />
      <circle cx={410} cy={y + 11} r="2.5" fill={fill} />
      <text x={418} y={y + 14} fontSize="8" fontWeight="700" fill={fill}>{label}</text>
      <polyline
        points={`560,${y + 14} 580,${y + 8} 600,${y + 12} 620,${y + 4} 640,${y + 9} 660,${y + 2}`}
        fill="none" stroke="url(#dm-spark)" strokeWidth="1.5"
        strokeLinecap="round" strokeLinejoin="round"
      />
    </g>
  );
}

export default DashboardMockup;
